# Generated by Django 3.2.23 on 2023-11-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_video_file_voicefile_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicefile',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='speeches/'),
        ),
    ]
